import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import { Suspense } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { CoinPriceProvider } from "@/context/PriceContext";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "./versatylorounded.ttf",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased bg-main-bg flex !relative flex-col items-center overflow-x-hidden md:bg-gradient-to-r from-fuchsia-500 to-cyan-500",
          myFont.className
        )}
      >
        <Suspense>
          <CoinPriceProvider>
            <div className="md:max-w-md w-full bg-main-bg relative">
              {children}
              <ToastContainer />
            </div>
          </CoinPriceProvider>
        </Suspense>
      </body>
    </html>
  );
}
